# Generated by Django 2.2.7 on 2019-12-08 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tipe', models.CharField(choices=[('Honda', 'honda'), ('Yamaha', 'yamaha')], max_length=100)),
                ('harga_sewa_hari', models.IntegerField(verbose_name='Price/Day')),
                ('lokasi', models.CharField(choices=[('Banda Aceh', 'banda aceh'), ('Aceh Besar', 'aceh besar')], max_length=100, verbose_name='City')),
                ('gambar', models.ImageField(upload_to='car/', verbose_name='Image')),
                ('deskripsi', models.TextField(verbose_name='Description')),
                ('slug', models.SlugField(editable=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Penyewaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_sewa', models.DateField(verbose_name='Start Date')),
                ('tgl_selesai', models.DateField(verbose_name='Finish Date')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Car')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pengecekan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('keterangan', models.TextField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Car')),
            ],
        ),
    ]
