# Generated by Django 2.2.7 on 2019-12-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tipe', models.CharField(max_length=100)),
                ('harga_sewa_hari', models.IntegerField()),
                ('lokasi', models.CharField(max_length=100)),
                ('gambar', models.ImageField(upload_to='')),
                ('deskripsi', models.TextField()),
            ],
        ),
    ]
