# Generated by Django 2.2.7 on 2019-12-13 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='pengecekan',
            old_name='admin_id',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='pengecekan',
            old_name='car_id',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='penyewaan',
            old_name='car_id',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='penyewaan',
            old_name='user_id',
            new_name='user',
        ),
    ]
