# Generated by Django 2.2.7 on 2019-12-03 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_pengecekan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengecekan',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
